In [ ]:
import numpy as np

# Zeros, Ones and full

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.full((3,2), 3.14)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

# linspace, arange

### linspace: Returns evenly spaced numbers over a specified interval
### arange: Returns evenly spaced values within a given interval



In [ ]:
np.arange(start=0, stop=5, step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.linspace(start=0, stop=5, num=10, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# Random

### 1) np.random.rand: generates random numbers uniformly distributed over the interval [0, 1)

In [ ]:
np.random.rand(3, 2)

array([[0.90816742, 0.88299123],
       [0.6408706 , 0.39836097],
       [0.57379797, 0.37180781]])

2) np.random.randn: generates random numbers from a standard normal distribution (mean 0 and variance 1)

In [ ]:
np.random.randn(3, 2)

array([[ 1.00908648, -0.55758   ],
       [-1.52233048, -0.60400903],
       [-1.68895267, -1.44524171]])

### 3) np.random.randint: This function generates random integers from a specified low (inclusive) to high (exclusive) range

In [ ]:
np.random.randint(1, 10, size=(3,2))

array([[6, 2],
       [1, 1],
       [8, 7]])

### 4) np.random.random: This function generates random floats in the half-open interval [0.0, 1.0)

In [ ]:
np.random.random((3,2))

array([[0.95651855, 0.93936584],
       [0.40304059, 0.63289178],
       [0.89350892, 0.45823557]])

### 5) np.random.choice: This function generates a random sample from a given 1-D array

In [ ]:
array = np.array([1, 2, 3, 4, 5])
np.random.choice(array, size=(3, 2))

array([[2, 3],
       [5, 2],
       [3, 5]])

### 6) np.random.shuffle: This function shuffles the elements of an array in place.

In [ ]:
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)
array

array([2, 3, 1, 5, 4])

### 7) np.random.normal: This function generates random numbers from a normal (Gaussian) distribution

In [ ]:
np.random.normal(loc=0.0, scale=1.0, size=(3,2))

array([[ 1.66315056,  0.11650381],
       [-0.63446541, -1.73889932],
       [-1.68838656,  0.06555748]])

### 8) np.random.uniform: This function generates random numbers from a uniform distribution.

In [ ]:
np.random.uniform(low=0.0, high=1.0, size=(3,2))

array([[0.73486654, 0.63029511],
       [0.15085302, 0.35271083],
       [0.47465901, 0.40646921]])

In [ ]:
arr = np.array([1,2,3,4,5])
arr[::-1]

array([5, 4, 3, 2, 1])

# Indexing and Slicing

## Indexing: Accessing each element of an array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[-1])

1
5


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr[0, 1])

2


## Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::2])

[2 3 4]
[1 2 3]
[4 5]
[1 3 5]


### Reversing an array

In [ ]:
arr = np.array([1,2,3,4,5])
arr[::-1]

array([5, 4, 3, 2, 1])

### Slicing of 2D array

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr[:, 1])
print(arr[1:, :2])

[2 5 8]
[[4 5]
 [7 8]]


### Integer indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print(arr[indices])

[1 3 5]


### Boolean indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
print(arr[mask])

[3 4 5]


# any() vs all()

In [ ]:
import numpy as np

arr = np.array([[False, False, False],
                [False, True, False],
                ])

print(np.any(arr))
print(np.any(arr, axis=0))
print(np.any(arr, axis=1))

True
[False  True False]
[False  True]


In [ ]:
import numpy as np

arr = np.array([[True, True, True],
                [False, True, True],
                [True, True, True]])

print(np.all(arr))
print(np.all(arr, axis=0))
print(np.all(arr, axis=1))

False
[False  True  True]
[ True False  True]


# Broadcasting

### 1) Broadcasting with scalars

In [ ]:
arr = np.array([1, 2, 3])
result = arr + 5
print(result)

[6 7 8]


### 2) Broadcasting with arrays of different shape

In [ ]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([10, 20, 30])

result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


# Reshape

### Reshaping to 1D array

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

reshaped_arr = arr.reshape((6,))
print(reshaped_arr)

[1 2 3 4 5 6]


In [ ]:
print(arr.reshape((-1,)))

[1 2 3 4 5 6]


### Reshaping to 2D array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


### Auto inference of a dimension

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = arr.reshape((2, -1))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


# Flatten vs Ravel
### Both converts multi-dimensional array into a 1D array

### 1) Flatten(): Returns a copy of the array collapsed into one **dimension**

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6]


In [ ]:
# Changes to flattened_arr do not affect arr
flattened_arr[0] = 10
print(arr)

[[1 2 3]
 [4 5 6]]


### 2) Ravel(): Returns a flattened 1D array as a view of the original array; Changes to ravelled array affects the original array

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

raveled_arr = arr.ravel()
print(raveled_arr)

[1 2 3 4 5 6]


In [ ]:
# Changes to raveled_arr affect arr
raveled_arr[0] = 10
print(arr)

[[10  2  3]
 [ 4  5  6]]


# Axis=1 vs Axis=0

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr, axis=0))

[5 7 9]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr, axis=1))

[ 6 15]


# Dot Product

In [40]:
# for 1D array

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
print(dot_product)

32


In [41]:
# for 2D array; follows matrix multiplication

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

dot_product = np.dot(A, B)
print(dot_product)

[[19 22]
 [43 50]]


# Cross Product

1) Cross product for 1D array

In [42]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

cross_product = np.cross(a, b)
print(cross_product)

[0 0 1]


# Linalg modules

## 1) Matrix Decomposition

In [44]:
# QR decomposition

A = np.array([[1, 2],
              [3, 4]])

Q, R = np.linalg.qr(A)
print("Orthogonal matrix Q:", Q)
print("Upper triangular matrix R:", R)

Orthogonal matrix Q: [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
Upper triangular matrix R: [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [45]:
# Cholesky decomposition

A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

L = np.linalg.cholesky(A)
print("Lower triangular matrix L:", L)

Lower triangular matrix L: [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [46]:
# Eigenvalue decomposition

A = np.array([[1, 2],
              [2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [ 3. -1.]
Eigenvectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [47]:
# SVD Decomposition

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, S, V = np.linalg.svd(A)
print("U:", U)
print("S:", S)
print("V:", V)

U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S: [9.52551809 0.51430058]
V: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# 2) Solving Linear Equations

In [48]:
# np.linalg.solve(); solves for x as Ax=b

A = np.array([[2, 3],
              [4, 5]])

b = np.array([1, 2])

x = np.linalg.solve(A, b)
print(x)

[0.5 0. ]


In [49]:
# np.linalg.lstsq(); solves the linear least square problems

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b = np.array([3, 7, 11])

x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)
print("Least-squares solution:", x)
print("Residuals:", residuals)
print("Rank of matrix:", rank)
print("Singular values:", singular_values)

Least-squares solution: [1. 1.]
Residuals: [1.23259516e-32]
Rank of matrix: 2
Singular values: [9.52551809 0.51430058]


# Matrix Norms

In [50]:
# Frobenius Norm

A = np.array([[1, 2],
              [3, 4]])

frobenius_norm = np.linalg.norm(A, ord='fro')
print("Frobenius Norm:", frobenius_norm)

Frobenius Norm: 5.477225575051661


In [53]:
# L1 Norm

A = np.array([[1, 2],
              [3, 4]])

l1_norm = np.linalg.norm(A, ord=1)
print("L1 Norm:", l1_norm)

L1 Norm: 6.0


In [54]:
# L2 Norm

A = np.array([[1, 2],
              [3, 4]])

l2_norm = np.linalg.norm(A, ord=2)
print("L2 Norm:", l2_norm)

L2 Norm: 5.464985704219043


# Determinant

In [55]:
A = np.array([[1, 2],
              [3, 4]])

determinant = np.linalg.det(A)
print("Determinant:", determinant)

Determinant: -2.0000000000000004


# Matrix Inverse

In [56]:
A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)
print("Inverse of A:")
print(A_inv)

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


# eye(): creates an identity matrix

In [59]:
identity_3x3 = np.eye(3)
print("2x2 Identity Matrix:")
print(identity_3x3)

2x2 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
